theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# GitHub Pages safe plugins only
plugins:
  - jekyll-default-layout
  - jekyll-optional-front-matter
  - jekyll-readme-index

# Enable relative links without extensions
relative_links:
  enabled: true
  collections: true

# Enable Mermaid diagram support
mermaid:
  enable: true