theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

# Enable Mermaid diagram support
mermaid:
  enable: true