name: Deploy Documentation to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install docsify-cli
      run: npm i docsify-cli -g

    - name: Build documentation
      run: |
        # Copy files to ensure proper structure
        mkdir -p dist
        cp -r docs dist/
        cp -r Research dist/
        cp index.html dist/
        cp _sidebar.md dist/
        cp _navbar.md dist/
        cp _coverpage.md dist/
        cp 404.md dist/
        cp .nojekyll dist/
        cp README.md dist/

        # Create a simple build verification
        echo "Documentation built successfully at $(date)" > dist/build-info.txt

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        enable_jekyll: false
        cname: # Add your custom domain here if you have one